# Generated by Django 4.0.1 on 2023-07-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cars_brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car_categories',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('image1', models.ImageField(default='default.png', upload_to='')),
                ('image2', models.ImageField(default='default.png', upload_to='')),
                ('image3', models.ImageField(default='default.png', upload_to='')),
                ('image4', models.ImageField(default='default.png', upload_to='')),
                ('probeg', models.IntegerField()),
                ('obyomdvigatela', models.IntegerField()),
                ('color', models.PositiveSmallIntegerField(choices=[(1, '1 - красный'), (2, '2 - зеленый'), (3, '3 - синий'), (4, '4 - белый'), (5, '5 - черный'), (6, '6 - серая')], null=True)),
                ('korobka', models.PositiveSmallIntegerField(choices=[(1, '1 - Автоматическая'), (2, '2 - Механическая')], null=True)),
                ('privod', models.PositiveSmallIntegerField(choices=[(1, '1 - Передний'), (2, '2 - задний'), (3, '3 - полный')], null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category')),
            ],
        ),
    ]
