# Generated by Django 4.0.1 on 2023-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image4',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'красный'), (2, 'зеленый'), (3, 'синий'), (4, 'белый'), (5, 'черный'), (6, 'серая')], null=True, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateField(verbose_name='дата произдводства'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='korobka',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Автоматическая'), (2, '2 - Механическая')], null=True, verbose_name='коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=50, verbose_name='полное название машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='obyomdvigatela',
            field=models.IntegerField(verbose_name='обьем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='privod',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Передний'), (2, '2 - задний'), (3, '3 - полный')], null=True, verbose_name='привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='probeg',
            field=models.IntegerField(verbose_name='пробег'),
        ),
    ]
