# Generated by Django 4.2.3 on 2023-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_image4_alter_car_color_alter_car_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
