# Generated by Django 4.2.3 on 2023-08-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_brand_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
