# Generated by Django 4.2.3 on 2023-08-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_testdrive_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[('красный', 'красный'), ('зеленый', 'зеленый'), ('синий', 'синий'), ('белый', 'белый'), ('черный', 'черный'), ('серая', 'серая')], null=True, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='korobka',
            field=models.PositiveSmallIntegerField(choices=[('Автоматическая', '1 - Автоматическая'), ('Механическая', '2 - Механическая')], null=True, verbose_name='коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='privod',
            field=models.PositiveSmallIntegerField(choices=[('Передняя', '1 - Передний'), ('Задняя', '2 - задний'), ('Полная', '3 - полный')], null=True, verbose_name='привод'),
        ),
    ]
