# Generated by Django 4.2.3 on 2023-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_color_alter_car_korobka_alter_car_privod'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
