# Generated by Django 4.2.3 on 2023-08-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
