# Generated by Django 4.2.3 on 2023-08-23 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0013_alter_car_color_alter_car_korobka_alter_car_privod'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
