# Generated by Django 4.2.3 on 2023-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_testdrive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('красный', 'красный'), ('зеленый', 'зеленый'), ('синий', 'синий'), ('белый', 'белый'), ('черный', 'черный'), ('серая', 'серая')], max_length=255, null=True),
        ),
    ]
